lane :test do
  try_scan(
    try_count: 2,
    scheme: 'sample-appSuccessfulTests'
  )

  try_scan(
    try_count: 10,
    scheme: 'sample-appParallelTests'
  )

  try_scan(
    try_count: 10,
    scheme: 'sample-appParallelUITests'
  )

  try_scan(
    try_count: 10,
    scheme: 'sample-appParallelTests',
    try_parallel: true,
    retry_parallel: false,
    parallel_workers: 2
  )
end
